#!/bin/sh

# Set these paths appropriately

BIN=/Users/sarakerr/PhD_Main/Pilot/TreeTagger/bin
CMD=/Users/sarakerr/PhD_Main/Pilot/TreeTagger/cmd
LIB=/Users/sarakerr/PhD_Main/Pilot/TreeTagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovenian-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
